# Copyright (c) Meta Platforms, Inc. and affiliates.

python_test(
  name = "tests",
  deps = [
    "//projects/jdwp/defs:defs",
    "//projects/jdwp/codegen:codegen",


  ],
  srcs = glob(["**/*.py"]),
)
