# Copyright (c) Meta Platforms, Inc. and affiliates.

genrule(
  name = "type-aliases",
  out = "type_aliases.py",
  cmd = "$(exe //projects/jdwp/codegen:generate-new-types) > $OUT",
)

genrule(
  name = "structs",
  out = "structs.py",
  cmd = "$(exe //projects/jdwp/codegen:generate-dataclasses) > $OUT",
)

python_library(
  name = "runtime",
  srcs = [
    ":structs",
    ":type-aliases",
    "async_streams.py",
    "jdwpstruct.py",
  ],
  visibility = ["PUBLIC", ],
  deps = [],
)
